# Generated by Django 4.1.7 on 2023-02-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_alter_party_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='party_images'),
        ),
    ]
