# Generated by Django 4.1.7 on 2023-02-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_alter_party_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
