# Generated by Django 4.1.4 on 2023-02-24 16:28

from django.db import migrations, models
import party.models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_alter_party_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=party.models.upload_to),
        ),
    ]
